sonar.projectKey=MechanicLtda
sonar.projectName=MechanicLtda
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Coverage
sonar.coverageReportPaths=coverage/SonarQubeCoverage.xml
sonar.cs.opencover.reportsPaths=coverage/SonarQubeCoverage.xml
