apiVersion: v1
kind: Service
metadata:
  name: mechanicltda-api
  namespace: mechanicltda
  labels:
    app.kubernetes.io/part-of: mechanicltda
    app.kubernetes.io/name: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: 8080
      targetPort: http
